version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: temp
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - minhaNetwork

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
    networks:
      - minhaNetwork

networks:
  minhaNetwork:

volumes:
  mysql_data:

